[project]
name = "mybrain-project"
version = "0.1.0"
description = "Program Analysis Of My Obsidian Vault"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "logging>=0.4.9.6",
    "python-dotenv>=1.0.1",
]
